version: "3.9"
services:
  mongo:
    image: mongo:6.0
    container_name: llm_app_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: llm_app_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/llmAppDb
      - MONGO_DB_NAME=llmAppDb
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-4o-mini
    depends_on:
      - mongo

volumes:
  mongo_data:
